CREATE TABLE [dbo].[Wine](
	[WineID] [int] IDENTITY(1,1) NOT NULL,
	[ProducerID] [int] NULL,
	[RegionID] [int] NULL,
	[Vintage] [int] NULL,
	[QualityControlID] [int] NULL,
	[VinyardEstateID] [int] NULL,
	[WineTypeID] [int] NULL,
	[Description] [nvarchar](100) NULL,
	[ABV] [decimal](4, 2) NULL,
	[Importer] [nvarchar](25) NULL,
	[Pats_Rating] [tinyint] NULL,
	[Pats_Comments] [nvarchar](200) NULL,
	[Mikes_Rating] [tinyint] NULL,
	[Mikes_Comments] [nvarchar](200) NULL,
	[InventoryLevel] [tinyint] NULL,
	[ExclusiveToRetailerID] [int] NULL,
	[DateCreated] [datetime2](3) NULL,
	[DateUpdated] [datetime2](3) NULL
) ON [PRIMARY]