INSERT INTO [dbo].[Country]
(
    [Name],
    [IsoCode],
    [DateUpdated],
    [DateCreated]
)
SELECT 'Afghanistan','AF',GETDATE(),GETDATE() UNION ALL
SELECT 'Albania','AL',GETDATE(),GETDATE() UNION ALL
SELECT 'Algeria','DZ',GETDATE(),GETDATE() UNION ALL
SELECT 'American Samoa','AS',GETDATE(),GETDATE() UNION ALL
SELECT 'Andorra','AD',GETDATE(),GETDATE() UNION ALL
SELECT 'Angola','AO',GETDATE(),GETDATE() UNION ALL
SELECT 'Anguilla','AI',GETDATE(),GETDATE() UNION ALL
SELECT 'Antarctica','AQ',GETDATE(),GETDATE() UNION ALL
SELECT 'Antigua and Barbuda','AG',GETDATE(),GETDATE() UNION ALL
SELECT 'Argentina','AR',GETDATE(),GETDATE() UNION ALL
SELECT 'Armenia','AM',GETDATE(),GETDATE() UNION ALL
SELECT 'Aruba','AW',GETDATE(),GETDATE() UNION ALL
SELECT 'Australia','AU',GETDATE(),GETDATE() UNION ALL
SELECT 'Austria','AT',GETDATE(),GETDATE() UNION ALL
SELECT 'Azerbaijan','AZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Bahamas','BS',GETDATE(),GETDATE() UNION ALL
SELECT 'Bahrain','BH',GETDATE(),GETDATE() UNION ALL
SELECT 'Bangladesh','BD',GETDATE(),GETDATE() UNION ALL
SELECT 'Barbados','BB',GETDATE(),GETDATE() UNION ALL
SELECT 'Belarus','BY',GETDATE(),GETDATE() UNION ALL
SELECT 'Belgium','BE',GETDATE(),GETDATE() UNION ALL
SELECT 'Belize','BZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Benin','BJ',GETDATE(),GETDATE() UNION ALL
SELECT 'Bermuda','BM',GETDATE(),GETDATE() UNION ALL
SELECT 'Bhutan','BT',GETDATE(),GETDATE() UNION ALL
SELECT 'Bolivia, Plurinational State of','BO',GETDATE(),GETDATE() UNION ALL
SELECT 'Bonaire, Sint Eustatius and Saba','BQ',GETDATE(),GETDATE() UNION ALL
SELECT 'Bosnia and Herzegovina','BA',GETDATE(),GETDATE() UNION ALL
SELECT 'Botswana','BW',GETDATE(),GETDATE() UNION ALL
SELECT 'Bouvet Island','BV',GETDATE(),GETDATE() UNION ALL
SELECT 'Brazil','BR',GETDATE(),GETDATE() UNION ALL
SELECT 'British Indian Ocean Territory','IO',GETDATE(),GETDATE() UNION ALL
SELECT 'Brunei Darussalam','BN',GETDATE(),GETDATE() UNION ALL
SELECT 'Bulgaria','BG',GETDATE(),GETDATE() UNION ALL
SELECT 'Burkina Faso','BF',GETDATE(),GETDATE() UNION ALL
SELECT 'Burundi','BI',GETDATE(),GETDATE() UNION ALL
SELECT 'Cambodia','KH',GETDATE(),GETDATE() UNION ALL
SELECT 'Cameroon','CM',GETDATE(),GETDATE() UNION ALL
SELECT 'Canada','CA',GETDATE(),GETDATE() UNION ALL
SELECT 'Cape Verde','CV',GETDATE(),GETDATE() UNION ALL
SELECT 'Cayman Islands','KY',GETDATE(),GETDATE() UNION ALL
SELECT 'Central African Republic','CF',GETDATE(),GETDATE() UNION ALL
SELECT 'Chad','TD',GETDATE(),GETDATE() UNION ALL
SELECT 'Chile','CL',GETDATE(),GETDATE() UNION ALL
SELECT 'China','CN',GETDATE(),GETDATE() UNION ALL
SELECT 'Christmas Island','CX',GETDATE(),GETDATE() UNION ALL
SELECT 'Cocos (Keeling) Islands','CC',GETDATE(),GETDATE() UNION ALL
SELECT 'Colombia','CO',GETDATE(),GETDATE() UNION ALL
SELECT 'Comoros','KM',GETDATE(),GETDATE() UNION ALL
SELECT 'Congo','CG',GETDATE(),GETDATE() UNION ALL
SELECT 'Congo, the Democratic Republic of the','CD',GETDATE(),GETDATE() UNION ALL
SELECT 'Cook Islands','CK',GETDATE(),GETDATE() UNION ALL
SELECT 'Costa Rica','CR',GETDATE(),GETDATE() UNION ALL
SELECT 'CÃ´te d''Ivoire','CI',GETDATE(),GETDATE() UNION ALL
SELECT 'Croatia','HR',GETDATE(),GETDATE() UNION ALL
SELECT 'Cuba','CU',GETDATE(),GETDATE() UNION ALL
SELECT 'CuraÃ§ao','CW',GETDATE(),GETDATE() UNION ALL
SELECT 'Cyprus','CY',GETDATE(),GETDATE() UNION ALL
SELECT 'Czech Republic','CZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Denmark','DK',GETDATE(),GETDATE() UNION ALL
SELECT 'Djibouti','DJ',GETDATE(),GETDATE() UNION ALL
SELECT 'Dominica','DM',GETDATE(),GETDATE() UNION ALL
SELECT 'Dominican Republic','DO',GETDATE(),GETDATE() UNION ALL
SELECT 'Ecuador','EC',GETDATE(),GETDATE() UNION ALL
SELECT 'Egypt','EG',GETDATE(),GETDATE() UNION ALL
SELECT 'El Salvador','SV',GETDATE(),GETDATE() UNION ALL
SELECT 'Equatorial Guinea','GQ',GETDATE(),GETDATE() UNION ALL
SELECT 'Eritrea','ER',GETDATE(),GETDATE() UNION ALL
SELECT 'Estonia','EE',GETDATE(),GETDATE() UNION ALL
SELECT 'Ethiopia','ET',GETDATE(),GETDATE() UNION ALL
SELECT 'Falkland Islands (Malvinas)','FK',GETDATE(),GETDATE() UNION ALL
SELECT 'Faroe Islands','FO',GETDATE(),GETDATE() UNION ALL
SELECT 'Fiji','FJ',GETDATE(),GETDATE() UNION ALL
SELECT 'Finland','FI',GETDATE(),GETDATE() UNION ALL
SELECT 'France','FR',GETDATE(),GETDATE() UNION ALL
SELECT 'French Guiana','GF',GETDATE(),GETDATE() UNION ALL
SELECT 'French Polynesia','PF',GETDATE(),GETDATE() UNION ALL
SELECT 'French Southern Territories','TF',GETDATE(),GETDATE() UNION ALL
SELECT 'Gabon','GA',GETDATE(),GETDATE() UNION ALL
SELECT 'Gambia','GM',GETDATE(),GETDATE() UNION ALL
SELECT 'Georgia','GE',GETDATE(),GETDATE() UNION ALL
SELECT 'Germany','DE',GETDATE(),GETDATE() UNION ALL
SELECT 'Ghana','GH',GETDATE(),GETDATE() UNION ALL
SELECT 'Gibraltar','GI',GETDATE(),GETDATE() UNION ALL
SELECT 'Greece','GR',GETDATE(),GETDATE() UNION ALL
SELECT 'Greenland','GL',GETDATE(),GETDATE() UNION ALL
SELECT 'Grenada','GD',GETDATE(),GETDATE() UNION ALL
SELECT 'Guadeloupe','GP',GETDATE(),GETDATE() UNION ALL
SELECT 'Guam','GU',GETDATE(),GETDATE() UNION ALL
SELECT 'Guatemala','GT',GETDATE(),GETDATE() UNION ALL
SELECT 'Guernsey','GG',GETDATE(),GETDATE() UNION ALL
SELECT 'Guinea','GN',GETDATE(),GETDATE() UNION ALL
SELECT 'Guinea-Bissau','GW',GETDATE(),GETDATE() UNION ALL
SELECT 'Guyana','GY',GETDATE(),GETDATE() UNION ALL
SELECT 'Haiti','HT',GETDATE(),GETDATE() UNION ALL
SELECT 'Heard Island and McDonald Islands','HM',GETDATE(),GETDATE() UNION ALL
SELECT 'Holy See (Vatican City State)','VA',GETDATE(),GETDATE() UNION ALL
SELECT 'Honduras','HN',GETDATE(),GETDATE() UNION ALL
SELECT 'Hong Kong','HK',GETDATE(),GETDATE() UNION ALL
SELECT 'Hungary','HU',GETDATE(),GETDATE() UNION ALL
SELECT 'Iceland','IS',GETDATE(),GETDATE() UNION ALL
SELECT 'India','IN',GETDATE(),GETDATE() UNION ALL
SELECT 'Indonesia','ID',GETDATE(),GETDATE() UNION ALL
SELECT 'Iran, Islamic Republic of','IR',GETDATE(),GETDATE() UNION ALL
SELECT 'Iraq','IQ',GETDATE(),GETDATE() UNION ALL
SELECT 'Ireland','IE',GETDATE(),GETDATE() UNION ALL
SELECT 'Isle of Man','IM',GETDATE(),GETDATE() UNION ALL
SELECT 'Israel','IL',GETDATE(),GETDATE() UNION ALL
SELECT 'Italy','IT',GETDATE(),GETDATE() UNION ALL
SELECT 'Jamaica','JM',GETDATE(),GETDATE() UNION ALL
SELECT 'Japan','JP',GETDATE(),GETDATE() UNION ALL
SELECT 'Jersey','JE',GETDATE(),GETDATE() UNION ALL
SELECT 'Jordan','JO',GETDATE(),GETDATE() UNION ALL
SELECT 'Kazakhstan','KZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Kenya','KE',GETDATE(),GETDATE() UNION ALL
SELECT 'Kiribati','KI',GETDATE(),GETDATE() UNION ALL
SELECT 'Korea, Democratic People''s Republic of','KP',GETDATE(),GETDATE() UNION ALL
SELECT 'Korea, Republic of','KR',GETDATE(),GETDATE() UNION ALL
SELECT 'Kuwait','KW',GETDATE(),GETDATE() UNION ALL
SELECT 'Kyrgyzstan','KG',GETDATE(),GETDATE() UNION ALL
SELECT 'Lao People''s Democratic Republic','LA',GETDATE(),GETDATE() UNION ALL
SELECT 'Latvia','LV',GETDATE(),GETDATE() UNION ALL
SELECT 'Lebanon','LB',GETDATE(),GETDATE() UNION ALL
SELECT 'Lesotho','LS',GETDATE(),GETDATE() UNION ALL
SELECT 'Liberia','LR',GETDATE(),GETDATE() UNION ALL
SELECT 'Libya','LY',GETDATE(),GETDATE() UNION ALL
SELECT 'Liechtenstein','LI',GETDATE(),GETDATE() UNION ALL
SELECT 'Lithuania','LT',GETDATE(),GETDATE() UNION ALL
SELECT 'Luxembourg','LU',GETDATE(),GETDATE() UNION ALL
SELECT 'Macao','MO',GETDATE(),GETDATE() UNION ALL
SELECT 'Macedonia, the Former Yugoslav Republic of','MK',GETDATE(),GETDATE() UNION ALL
SELECT 'Madagascar','MG',GETDATE(),GETDATE() UNION ALL
SELECT 'Malawi','MW',GETDATE(),GETDATE() UNION ALL
SELECT 'Malaysia','MY',GETDATE(),GETDATE() UNION ALL
SELECT 'Maldives','MV',GETDATE(),GETDATE() UNION ALL
SELECT 'Mali','ML',GETDATE(),GETDATE() UNION ALL
SELECT 'Malta','MT',GETDATE(),GETDATE() UNION ALL
SELECT 'Marshall Islands','MH',GETDATE(),GETDATE() UNION ALL
SELECT 'Martinique','MQ',GETDATE(),GETDATE() UNION ALL
SELECT 'Mauritania','MR',GETDATE(),GETDATE() UNION ALL
SELECT 'Mauritius','MU',GETDATE(),GETDATE() UNION ALL
SELECT 'Mayotte','YT',GETDATE(),GETDATE() UNION ALL
SELECT 'Mexico','MX',GETDATE(),GETDATE() UNION ALL
SELECT 'Micronesia, Federated States of','FM',GETDATE(),GETDATE() UNION ALL
SELECT 'Moldova, Republic of','MD',GETDATE(),GETDATE() UNION ALL
SELECT 'Monaco','MC',GETDATE(),GETDATE() UNION ALL
SELECT 'Mongolia','MN',GETDATE(),GETDATE() UNION ALL
SELECT 'Montenegro','ME',GETDATE(),GETDATE() UNION ALL
SELECT 'Montserrat','MS',GETDATE(),GETDATE() UNION ALL
SELECT 'Morocco','MA',GETDATE(),GETDATE() UNION ALL
SELECT 'Mozambique','MZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Myanmar','MM',GETDATE(),GETDATE() UNION ALL
SELECT 'Namibia','NA',GETDATE(),GETDATE() UNION ALL
SELECT 'Nauru','NR',GETDATE(),GETDATE() UNION ALL
SELECT 'Nepal','NP',GETDATE(),GETDATE() UNION ALL
SELECT 'Netherlands','NL',GETDATE(),GETDATE() UNION ALL
SELECT 'New Caledonia','NC',GETDATE(),GETDATE() UNION ALL
SELECT 'New Zealand','NZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Nicaragua','NI',GETDATE(),GETDATE() UNION ALL
SELECT 'Niger','NE',GETDATE(),GETDATE() UNION ALL
SELECT 'Nigeria','NG',GETDATE(),GETDATE() UNION ALL
SELECT 'Niue','NU',GETDATE(),GETDATE() UNION ALL
SELECT 'Norfolk Island','NF',GETDATE(),GETDATE() UNION ALL
SELECT 'Northern Mariana Islands','MP',GETDATE(),GETDATE() UNION ALL
SELECT 'Norway','NO',GETDATE(),GETDATE() UNION ALL
SELECT 'Oman','OM',GETDATE(),GETDATE() UNION ALL
SELECT 'Pakistan','PK',GETDATE(),GETDATE() UNION ALL
SELECT 'Palau','PW',GETDATE(),GETDATE() UNION ALL
SELECT 'Palestine, State of','PS',GETDATE(),GETDATE() UNION ALL
SELECT 'Panama','PA',GETDATE(),GETDATE() UNION ALL
SELECT 'Papua New Guinea','PG',GETDATE(),GETDATE() UNION ALL
SELECT 'Paraguay','PY',GETDATE(),GETDATE() UNION ALL
SELECT 'Peru','PE',GETDATE(),GETDATE() UNION ALL
SELECT 'Philippines','PH',GETDATE(),GETDATE() UNION ALL
SELECT 'Pitcairn','PN',GETDATE(),GETDATE() UNION ALL
SELECT 'Poland','PL',GETDATE(),GETDATE() UNION ALL
SELECT 'Portugal','PT',GETDATE(),GETDATE() UNION ALL
SELECT 'Puerto Rico','PR',GETDATE(),GETDATE() UNION ALL
SELECT 'Qatar','QA',GETDATE(),GETDATE() UNION ALL
SELECT 'RÃ©union','RE',GETDATE(),GETDATE() UNION ALL
SELECT 'Romania','RO',GETDATE(),GETDATE() UNION ALL
SELECT 'Russian Federation','RU',GETDATE(),GETDATE() UNION ALL
SELECT 'Rwanda','RW',GETDATE(),GETDATE() UNION ALL
SELECT 'Saint BarthÃ©lemy','BL',GETDATE(),GETDATE() UNION ALL
SELECT 'Saint Helena, Ascension and Tristan da Cunha','SH',GETDATE(),GETDATE() UNION ALL
SELECT 'Saint Kitts and Nevis','KN',GETDATE(),GETDATE() UNION ALL
SELECT 'Saint Lucia','LC',GETDATE(),GETDATE() UNION ALL
SELECT 'Saint Martin (French part)','MF',GETDATE(),GETDATE() UNION ALL
SELECT 'Saint Pierre and Miquelon','PM',GETDATE(),GETDATE() UNION ALL
SELECT 'Saint Vincent and the Grenadines','VC',GETDATE(),GETDATE() UNION ALL
SELECT 'Samoa','WS',GETDATE(),GETDATE() UNION ALL
SELECT 'San Marino','SM',GETDATE(),GETDATE() UNION ALL
SELECT 'Sao Tome and Principe','ST',GETDATE(),GETDATE() UNION ALL
SELECT 'Saudi Arabia','SA',GETDATE(),GETDATE() UNION ALL
SELECT 'Senegal','SN',GETDATE(),GETDATE() UNION ALL
SELECT 'Serbia','RS',GETDATE(),GETDATE() UNION ALL
SELECT 'Seychelles','SC',GETDATE(),GETDATE() UNION ALL
SELECT 'Sierra Leone','SL',GETDATE(),GETDATE() UNION ALL
SELECT 'Singapore','SG',GETDATE(),GETDATE() UNION ALL
SELECT 'Sint Maarten (Dutch part)','SX',GETDATE(),GETDATE() UNION ALL
SELECT 'Slovakia','SK',GETDATE(),GETDATE() UNION ALL
SELECT 'Slovenia','SI',GETDATE(),GETDATE() UNION ALL
SELECT 'Solomon Islands','SB',GETDATE(),GETDATE() UNION ALL
SELECT 'Somalia','SO',GETDATE(),GETDATE() UNION ALL
SELECT 'South Africa','ZA',GETDATE(),GETDATE() UNION ALL
SELECT 'South Georgia and the South Sandwich Islands','GS',GETDATE(),GETDATE() UNION ALL
SELECT 'South Sudan','SS',GETDATE(),GETDATE() UNION ALL
SELECT 'Spain','ES',GETDATE(),GETDATE() UNION ALL
SELECT 'Sri Lanka','LK',GETDATE(),GETDATE() UNION ALL
SELECT 'Sudan','SD',GETDATE(),GETDATE() UNION ALL
SELECT 'Suriname','SR',GETDATE(),GETDATE() UNION ALL
SELECT 'Svalbard and Jan Mayen','SJ',GETDATE(),GETDATE() UNION ALL
SELECT 'Swaziland','SZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Sweden','SE',GETDATE(),GETDATE() UNION ALL
SELECT 'Switzerland','CH',GETDATE(),GETDATE() UNION ALL
SELECT 'Syrian Arab Republic','SY',GETDATE(),GETDATE() UNION ALL
SELECT 'Taiwan, Province of China','TW',GETDATE(),GETDATE() UNION ALL
SELECT 'Tajikistan','TJ',GETDATE(),GETDATE() UNION ALL
SELECT 'Tanzania, United Republic of','TZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Thailand','TH',GETDATE(),GETDATE() UNION ALL
SELECT 'Timor-Leste','TL',GETDATE(),GETDATE() UNION ALL
SELECT 'Togo','TG',GETDATE(),GETDATE() UNION ALL
SELECT 'Tokelau','TK',GETDATE(),GETDATE() UNION ALL
SELECT 'Tonga','TO',GETDATE(),GETDATE() UNION ALL
SELECT 'Trinidad and Tobago','TT',GETDATE(),GETDATE() UNION ALL
SELECT 'Tunisia','TN',GETDATE(),GETDATE() UNION ALL
SELECT 'Turkey','TR',GETDATE(),GETDATE() UNION ALL
SELECT 'Turkmenistan','TM',GETDATE(),GETDATE() UNION ALL
SELECT 'Turks and Caicos Islands','TC',GETDATE(),GETDATE() UNION ALL
SELECT 'Tuvalu','TV',GETDATE(),GETDATE() UNION ALL
SELECT 'Uganda','UG',GETDATE(),GETDATE() UNION ALL
SELECT 'Ukraine','UA',GETDATE(),GETDATE() UNION ALL
SELECT 'United Arab Emirates','AE',GETDATE(),GETDATE() UNION ALL
SELECT 'United Kingdom','GB',GETDATE(),GETDATE() UNION ALL
SELECT 'United States','US',GETDATE(),GETDATE() UNION ALL
SELECT 'United States Minor Outlying Islands','UM',GETDATE(),GETDATE() UNION ALL
SELECT 'Uruguay','UY',GETDATE(),GETDATE() UNION ALL
SELECT 'Uzbekistan','UZ',GETDATE(),GETDATE() UNION ALL
SELECT 'Vanuatu','VU',GETDATE(),GETDATE() UNION ALL
SELECT 'Venezuela, Bolivarian Republic of','VE',GETDATE(),GETDATE() UNION ALL
SELECT 'Viet Nam','VN',GETDATE(),GETDATE() UNION ALL
SELECT 'Virgin Islands, British','VG',GETDATE(),GETDATE() UNION ALL
SELECT 'Virgin Islands, U.S.','VI',GETDATE(),GETDATE() UNION ALL
SELECT 'Wallis and Futuna','WF',GETDATE(),GETDATE() UNION ALL
SELECT 'Western Sahara','EH',GETDATE(),GETDATE() UNION ALL
SELECT 'Yemen','YE',GETDATE(),GETDATE() UNION ALL
SELECT 'Zambia','ZM',GETDATE(),GETDATE() UNION ALL
SELECT 'Zimbabwe','ZW',GETDATE(),GETDATE();